//! Raw FFI bindings to libhamlib, generated by bindgen.
//!
//! Prefer the safe wrappers in `quirq-core` over these types directly.
#![allow(non_upper_case_globals, non_camel_case_types, non_snake_case, dead_code)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
