// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `lock`, `parse_func`, `parse_level`, `parse_mode`, `parse_parm`, `parse_power_state`, `parse_rptr_shift`, `parse_vfo_op`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`, `from`

/// Returns all radio models available through `driver`.
///
/// The returned list can be presented directly in a radio-selection UI.
/// When the user picks a model, pass `model.driver` and
/// `[("model", model.driver_model_id), ("port", ...)]` to `RigHandle::open()`.
Future<List<RadioModel>> listModels({required String driver}) =>
    RustLib.instance.api.crateApiListModels(driver: driver);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RigHandle>>
abstract class RigHandle implements RustOpaqueInterface {
  /// Returns the CTCSS squelch tone in units of 0.1 Hz.
  Future<int> getCtcssSql({required String vfo});

  /// Returns the CTCSS TX tone in units of 0.1 Hz (e.g. 1318 = 131.8 Hz).
  Future<int> getCtcssTone({required String vfo});

  /// Returns the DCS TX code.
  Future<int> getDcsCode({required String vfo});

  /// Returns the frequency of `vfo` in Hz.
  Future<BigInt> getFreq({required String vfo});

  /// Returns `true` if `func` is enabled on `vfo`.
  /// Use `supported_funcs()` to obtain valid function names.
  Future<bool> getFunc({required String vfo, required String func});

  /// Returns the radio's identification string.
  Future<String> getInfo();

  /// Returns the value of `level` on `vfo`.
  /// Use `supported_levels()` to obtain valid level names.
  Future<LevelValue> getLevel({required String vfo, required String level});

  /// Returns `(mode_name, passband_hz)` for `vfo`.
  /// `passband_hz` is `None` when the radio reports its default bandwidth.
  Future<(String, int?)> getMode({required String vfo});

  /// Returns the value of a radio-wide parameter.
  Future<LevelValue> getParm({required String parm});

  /// Returns the radio power state: `"On"`, `"Off"`, `"Standby"`, or `"Operate"`.
  Future<String> getPowerstat();

  /// Returns `true` if the radio is transmitting.
  Future<bool> getPtt();

  /// Returns the RIT (Receive Incremental Tuning) offset in Hz.
  Future<PlatformInt64> getRit({required String vfo});

  /// Returns the repeater offset in Hz.
  Future<PlatformInt64> getRptrOffs({required String vfo});

  /// Returns the repeater shift direction: `"Simplex"`, `"Plus"`, or `"Minus"`.
  Future<String> getRptrShift({required String vfo});

  /// Returns the TX frequency in Hz when in split mode.
  Future<BigInt> getSplitFreq({required String txVfo});

  /// Returns `(split_enabled, tx_vfo_name)` for `rx_vfo`.
  Future<(bool, String)> getSplitVfo({required String rxVfo});

  /// Returns the VFO tuning step in Hz.
  Future<BigInt> getTs({required String vfo});

  /// Returns the XIT (Transmit Incremental Tuning) offset in Hz.
  Future<PlatformInt64> getXit({required String vfo});

  /// Open a connection to a radio transceiver.
  ///
  /// `driver` selects the backend. `params` supplies driver-specific
  /// key-value configuration. Callers never need to import driver-specific
  /// types or constants.
  ///
  /// ## Supported drivers
  ///
  /// **`"hamlib"`** — any radio supported by libhamlib.
  /// - `"model"` — hamlib model number as a decimal string (e.g. `"3085"` for IC-705).
  ///   Run `rigctl --list` to find the number for a specific radio.
  /// - `"port"` — device path or hostname (e.g. `"/dev/ttyUSB0"`, `"192.168.1.100"`).
  ///
  /// Additional drivers (e.g. `"icom-lan"`) will be added here as they are
  /// implemented. The set of recognised param keys is documented per driver.
  static Future<RigHandle> open({
    required String driver,
    required List<KeyValue> params,
  }) => RustLib.instance.api.crateApiRigHandleOpen(
    driver: driver,
    params: params,
  );

  static Future<RigHandle> openHamlibRaw({
    required int model,
    required String port,
  }) => RustLib.instance.api.crateApiRigHandleOpenHamlibRaw(
    model: model,
    port: port,
  );

  /// Sets the CTCSS squelch tone in units of 0.1 Hz.
  Future<void> setCtcssSql({required String vfo, required int tone});

  /// Sets the CTCSS TX tone in units of 0.1 Hz.
  Future<void> setCtcssTone({required String vfo, required int tone});

  /// Sets the DCS TX code.
  Future<void> setDcsCode({required String vfo, required int code});

  /// Sets the frequency of `vfo` to `hz` Hz.
  Future<void> setFreq({required String vfo, required BigInt hz});

  /// Enables or disables `func` on `vfo`.
  Future<void> setFunc({
    required String vfo,
    required String func,
    required bool enabled,
  });

  /// Sets `level` on `vfo` to `value`.
  Future<void> setLevel({
    required String vfo,
    required String level,
    required LevelValue value,
  });

  /// Sets the mode and optional passband width (Hz) on `vfo`.
  /// Pass `None` for `passband_hz` to use the radio's default width for the mode.
  Future<void> setMode({
    required String vfo,
    required String mode,
    int? passbandHz,
  });

  /// Sets a radio-wide parameter.
  Future<void> setParm({required String parm, required LevelValue value});

  /// Sets the radio power state. Accepts `"On"`, `"Off"`, `"Standby"`, or `"Operate"`.
  Future<void> setPowerstat({required String state});

  /// Keys the transmitter if `tx` is `true`, releases it if `false`.
  Future<void> setPtt({required bool tx});

  /// Sets the RIT offset in Hz (negative to tune down).
  Future<void> setRit({required String vfo, required PlatformInt64 hz});

  /// Sets the repeater offset in Hz.
  Future<void> setRptrOffs({required String vfo, required PlatformInt64 hz});

  /// Sets the repeater shift direction. Accepts `"Simplex"`, `"Plus"`, `"Minus"`,
  /// `"None"`, `"+"`, or `"-"` (case-insensitive).
  Future<void> setRptrShift({required String vfo, required String shift});

  /// Sets the TX frequency in Hz when in split mode.
  Future<void> setSplitFreq({required String txVfo, required BigInt hz});

  /// Enables or disables split, assigning `tx_vfo` as the transmit VFO.
  Future<void> setSplitVfo({
    required String rxVfo,
    required bool split,
    required String txVfo,
  });

  /// Sets the VFO tuning step in Hz.
  Future<void> setTs({required String vfo, required BigInt hz});

  /// Sets the XIT offset in Hz.
  Future<void> setXit({required String vfo, required PlatformInt64 hz});

  /// Returns the function names this radio supports (e.g. `["Noise Blanker", "VOX"]`).
  Future<List<String>> supportedFuncs();

  /// Returns the level names this radio supports (e.g. `["AF Gain", "RF Power"]`).
  Future<List<String>> supportedLevels();

  /// Returns the mode names this radio supports (e.g. `["USB", "LSB", "CW"]`).
  Future<List<String>> supportedModes();

  /// Returns the VFO operation names this radio supports.
  Future<List<String>> supportedVfoOps();

  /// Returns the canonical name for `name` if this radio has such a VFO,
  /// or `None` if it does not. Accepts driver aliases (e.g. `"VFOA"` for `"A"`).
  Future<String?> vfoByName({required String name});

  /// Returns the VFO names supported by this radio (e.g. `["A", "B", "Current"]`).
  Future<List<String>> vfoList();

  /// Executes a discrete VFO operation (e.g. `"Toggle A/B"`, `"Copy A→B"`).
  /// Use `supported_vfo_ops()` to obtain the list of valid operation names.
  Future<void> vfoOp({required String vfo, required String op});
}

/// A key-value pair used for driver configuration in `RigHandle::open`.
/// FRB v2 does not support Rust tuples across the FFI boundary; this struct
/// is the equivalent.
class KeyValue {
  final String key;
  final String value;

  const KeyValue({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyValue &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

@freezed
sealed class LevelValue with _$LevelValue {
  const LevelValue._();

  const factory LevelValue.float(double field0) = LevelValue_Float;
  const factory LevelValue.int(int field0) = LevelValue_Int;
}

/// Describes a single radio model available through a particular driver.
///
/// `driver` and `driver_model_id` together identify the model in a way that
/// can be passed directly back to `RigHandle::open()` — Dart never needs to
/// parse or understand either value.
class RadioModel {
  /// The driver that supports this model (e.g. `"hamlib"`).
  final String driver;

  /// Opaque driver-internal model identifier.  Pass this as the `"model"`
  /// entry in the `params` argument to `RigHandle::open()`.
  final String driverModelId;
  final String manufacturer;
  final String model;
  final String version;

  /// Human-readable status: `"Stable"`, `"Beta"`, `"Alpha"`, `"Untested"`, `"Buggy"`.
  final String status;

  const RadioModel({
    required this.driver,
    required this.driverModelId,
    required this.manufacturer,
    required this.model,
    required this.version,
    required this.status,
  });

  @override
  int get hashCode =>
      driver.hashCode ^
      driverModelId.hashCode ^
      manufacturer.hashCode ^
      model.hashCode ^
      version.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RadioModel &&
          runtimeType == other.runtimeType &&
          driver == other.driver &&
          driverModelId == other.driverModelId &&
          manufacturer == other.manufacturer &&
          model == other.model &&
          version == other.version &&
          status == other.status;
}
