// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiFrbInit();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 220034269;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'quirq_ffi',
        ioDirectory: '../lib/quirq-ffi/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<int> crateApiRigHandleGetCtcssSql({
    required RigHandle that,
    required String vfo,
  });

  Future<int> crateApiRigHandleGetCtcssTone({
    required RigHandle that,
    required String vfo,
  });

  Future<int> crateApiRigHandleGetDcsCode({
    required RigHandle that,
    required String vfo,
  });

  Future<BigInt> crateApiRigHandleGetFreq({
    required RigHandle that,
    required String vfo,
  });

  Future<bool> crateApiRigHandleGetFunc({
    required RigHandle that,
    required String vfo,
    required String func,
  });

  Future<String> crateApiRigHandleGetInfo({required RigHandle that});

  Future<LevelValue> crateApiRigHandleGetLevel({
    required RigHandle that,
    required String vfo,
    required String level,
  });

  Future<(String, int?)> crateApiRigHandleGetMode({
    required RigHandle that,
    required String vfo,
  });

  Future<LevelValue> crateApiRigHandleGetParm({
    required RigHandle that,
    required String parm,
  });

  Future<String> crateApiRigHandleGetPowerstat({required RigHandle that});

  Future<bool> crateApiRigHandleGetPtt({required RigHandle that});

  Future<PlatformInt64> crateApiRigHandleGetRit({
    required RigHandle that,
    required String vfo,
  });

  Future<PlatformInt64> crateApiRigHandleGetRptrOffs({
    required RigHandle that,
    required String vfo,
  });

  Future<String> crateApiRigHandleGetRptrShift({
    required RigHandle that,
    required String vfo,
  });

  Future<BigInt> crateApiRigHandleGetSplitFreq({
    required RigHandle that,
    required String txVfo,
  });

  Future<(bool, String)> crateApiRigHandleGetSplitVfo({
    required RigHandle that,
    required String rxVfo,
  });

  Future<BigInt> crateApiRigHandleGetTs({
    required RigHandle that,
    required String vfo,
  });

  Future<PlatformInt64> crateApiRigHandleGetXit({
    required RigHandle that,
    required String vfo,
  });

  Future<RigHandle> crateApiRigHandleOpen({
    required String driver,
    required List<KeyValue> params,
  });

  Future<RigHandle> crateApiRigHandleOpenHamlibRaw({
    required int model,
    required String port,
  });

  Future<void> crateApiRigHandleSetCtcssSql({
    required RigHandle that,
    required String vfo,
    required int tone,
  });

  Future<void> crateApiRigHandleSetCtcssTone({
    required RigHandle that,
    required String vfo,
    required int tone,
  });

  Future<void> crateApiRigHandleSetDcsCode({
    required RigHandle that,
    required String vfo,
    required int code,
  });

  Future<void> crateApiRigHandleSetFreq({
    required RigHandle that,
    required String vfo,
    required BigInt hz,
  });

  Future<void> crateApiRigHandleSetFunc({
    required RigHandle that,
    required String vfo,
    required String func,
    required bool enabled,
  });

  Future<void> crateApiRigHandleSetLevel({
    required RigHandle that,
    required String vfo,
    required String level,
    required LevelValue value,
  });

  Future<void> crateApiRigHandleSetMode({
    required RigHandle that,
    required String vfo,
    required String mode,
    int? passbandHz,
  });

  Future<void> crateApiRigHandleSetParm({
    required RigHandle that,
    required String parm,
    required LevelValue value,
  });

  Future<void> crateApiRigHandleSetPowerstat({
    required RigHandle that,
    required String state,
  });

  Future<void> crateApiRigHandleSetPtt({
    required RigHandle that,
    required bool tx,
  });

  Future<void> crateApiRigHandleSetRit({
    required RigHandle that,
    required String vfo,
    required PlatformInt64 hz,
  });

  Future<void> crateApiRigHandleSetRptrOffs({
    required RigHandle that,
    required String vfo,
    required PlatformInt64 hz,
  });

  Future<void> crateApiRigHandleSetRptrShift({
    required RigHandle that,
    required String vfo,
    required String shift,
  });

  Future<void> crateApiRigHandleSetSplitFreq({
    required RigHandle that,
    required String txVfo,
    required BigInt hz,
  });

  Future<void> crateApiRigHandleSetSplitVfo({
    required RigHandle that,
    required String rxVfo,
    required bool split,
    required String txVfo,
  });

  Future<void> crateApiRigHandleSetTs({
    required RigHandle that,
    required String vfo,
    required BigInt hz,
  });

  Future<void> crateApiRigHandleSetXit({
    required RigHandle that,
    required String vfo,
    required PlatformInt64 hz,
  });

  Future<List<String>> crateApiRigHandleSupportedFuncs({
    required RigHandle that,
  });

  Future<List<String>> crateApiRigHandleSupportedLevels({
    required RigHandle that,
  });

  Future<List<String>> crateApiRigHandleSupportedModes({
    required RigHandle that,
  });

  Future<List<String>> crateApiRigHandleSupportedVfoOps({
    required RigHandle that,
  });

  Future<String?> crateApiRigHandleVfoByName({
    required RigHandle that,
    required String name,
  });

  Future<List<String>> crateApiRigHandleVfoList({required RigHandle that});

  Future<void> crateApiRigHandleVfoOp({
    required RigHandle that,
    required String vfo,
    required String op,
  });

  Future<void> crateApiFrbInit();

  Future<List<RadioModel>> crateApiListModels({required String driver});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RigHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RigHandle;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RigHandlePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<int> crateApiRigHandleGetCtcssSql({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetCtcssSqlConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetCtcssSqlConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_ctcss_sql",
        argNames: ["that", "vfo"],
      );

  @override
  Future<int> crateApiRigHandleGetCtcssTone({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetCtcssToneConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetCtcssToneConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_ctcss_tone",
        argNames: ["that", "vfo"],
      );

  @override
  Future<int> crateApiRigHandleGetDcsCode({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetDcsCodeConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetDcsCodeConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_dcs_code",
        argNames: ["that", "vfo"],
      );

  @override
  Future<BigInt> crateApiRigHandleGetFreq({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetFreqConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetFreqConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_freq",
    argNames: ["that", "vfo"],
  );

  @override
  Future<bool> crateApiRigHandleGetFunc({
    required RigHandle that,
    required String vfo,
    required String func,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(func, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetFuncConstMeta,
        argValues: [that, vfo, func],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetFuncConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_func",
    argNames: ["that", "vfo", "func"],
  );

  @override
  Future<String> crateApiRigHandleGetInfo({required RigHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetInfoConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetInfoConstMeta =>
      const TaskConstMeta(debugName: "RigHandle_get_info", argNames: ["that"]);

  @override
  Future<LevelValue> crateApiRigHandleGetLevel({
    required RigHandle that,
    required String vfo,
    required String level,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(level, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_level_value,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetLevelConstMeta,
        argValues: [that, vfo, level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetLevelConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_level",
    argNames: ["that", "vfo", "level"],
  );

  @override
  Future<(String, int?)> crateApiRigHandleGetMode({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_string_opt_box_autoadd_u_32,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetModeConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetModeConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_mode",
    argNames: ["that", "vfo"],
  );

  @override
  Future<LevelValue> crateApiRigHandleGetParm({
    required RigHandle that,
    required String parm,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(parm, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_level_value,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetParmConstMeta,
        argValues: [that, parm],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetParmConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_parm",
    argNames: ["that", "parm"],
  );

  @override
  Future<String> crateApiRigHandleGetPowerstat({required RigHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetPowerstatConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetPowerstatConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_powerstat",
        argNames: ["that"],
      );

  @override
  Future<bool> crateApiRigHandleGetPtt({required RigHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetPttConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetPttConstMeta =>
      const TaskConstMeta(debugName: "RigHandle_get_ptt", argNames: ["that"]);

  @override
  Future<PlatformInt64> crateApiRigHandleGetRit({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetRitConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetRitConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_rit",
    argNames: ["that", "vfo"],
  );

  @override
  Future<PlatformInt64> crateApiRigHandleGetRptrOffs({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetRptrOffsConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetRptrOffsConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_rptr_offs",
        argNames: ["that", "vfo"],
      );

  @override
  Future<String> crateApiRigHandleGetRptrShift({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetRptrShiftConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetRptrShiftConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_rptr_shift",
        argNames: ["that", "vfo"],
      );

  @override
  Future<BigInt> crateApiRigHandleGetSplitFreq({
    required RigHandle that,
    required String txVfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(txVfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetSplitFreqConstMeta,
        argValues: [that, txVfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetSplitFreqConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_split_freq",
        argNames: ["that", "txVfo"],
      );

  @override
  Future<(bool, String)> crateApiRigHandleGetSplitVfo({
    required RigHandle that,
    required String rxVfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(rxVfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_record_bool_string,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetSplitVfoConstMeta,
        argValues: [that, rxVfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetSplitVfoConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_get_split_vfo",
        argNames: ["that", "rxVfo"],
      );

  @override
  Future<BigInt> crateApiRigHandleGetTs({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetTsConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetTsConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_ts",
    argNames: ["that", "vfo"],
  );

  @override
  Future<PlatformInt64> crateApiRigHandleGetXit({
    required RigHandle that,
    required String vfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleGetXitConstMeta,
        argValues: [that, vfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleGetXitConstMeta => const TaskConstMeta(
    debugName: "RigHandle_get_xit",
    argNames: ["that", "vfo"],
  );

  @override
  Future<RigHandle> crateApiRigHandleOpen({
    required String driver,
    required List<KeyValue> params,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(driver, serializer);
          sse_encode_list_key_value(params, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleOpenConstMeta,
        argValues: [driver, params],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleOpenConstMeta => const TaskConstMeta(
    debugName: "RigHandle_open",
    argNames: ["driver", "params"],
  );

  @override
  Future<RigHandle> crateApiRigHandleOpenHamlibRaw({
    required int model,
    required String port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(model, serializer);
          sse_encode_String(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleOpenHamlibRawConstMeta,
        argValues: [model, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleOpenHamlibRawConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_open_hamlib_raw",
        argNames: ["model", "port"],
      );

  @override
  Future<void> crateApiRigHandleSetCtcssSql({
    required RigHandle that,
    required String vfo,
    required int tone,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_u_32(tone, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetCtcssSqlConstMeta,
        argValues: [that, vfo, tone],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetCtcssSqlConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_ctcss_sql",
        argNames: ["that", "vfo", "tone"],
      );

  @override
  Future<void> crateApiRigHandleSetCtcssTone({
    required RigHandle that,
    required String vfo,
    required int tone,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_u_32(tone, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetCtcssToneConstMeta,
        argValues: [that, vfo, tone],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetCtcssToneConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_ctcss_tone",
        argNames: ["that", "vfo", "tone"],
      );

  @override
  Future<void> crateApiRigHandleSetDcsCode({
    required RigHandle that,
    required String vfo,
    required int code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_u_32(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetDcsCodeConstMeta,
        argValues: [that, vfo, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetDcsCodeConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_dcs_code",
        argNames: ["that", "vfo", "code"],
      );

  @override
  Future<void> crateApiRigHandleSetFreq({
    required RigHandle that,
    required String vfo,
    required BigInt hz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_u_64(hz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetFreqConstMeta,
        argValues: [that, vfo, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetFreqConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_freq",
    argNames: ["that", "vfo", "hz"],
  );

  @override
  Future<void> crateApiRigHandleSetFunc({
    required RigHandle that,
    required String vfo,
    required String func,
    required bool enabled,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(func, serializer);
          sse_encode_bool(enabled, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetFuncConstMeta,
        argValues: [that, vfo, func, enabled],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetFuncConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_func",
    argNames: ["that", "vfo", "func", "enabled"],
  );

  @override
  Future<void> crateApiRigHandleSetLevel({
    required RigHandle that,
    required String vfo,
    required String level,
    required LevelValue value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(level, serializer);
          sse_encode_box_autoadd_level_value(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetLevelConstMeta,
        argValues: [that, vfo, level, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetLevelConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_level",
    argNames: ["that", "vfo", "level", "value"],
  );

  @override
  Future<void> crateApiRigHandleSetMode({
    required RigHandle that,
    required String vfo,
    required String mode,
    int? passbandHz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(mode, serializer);
          sse_encode_opt_box_autoadd_u_32(passbandHz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetModeConstMeta,
        argValues: [that, vfo, mode, passbandHz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetModeConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_mode",
    argNames: ["that", "vfo", "mode", "passbandHz"],
  );

  @override
  Future<void> crateApiRigHandleSetParm({
    required RigHandle that,
    required String parm,
    required LevelValue value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(parm, serializer);
          sse_encode_box_autoadd_level_value(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetParmConstMeta,
        argValues: [that, parm, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetParmConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_parm",
    argNames: ["that", "parm", "value"],
  );

  @override
  Future<void> crateApiRigHandleSetPowerstat({
    required RigHandle that,
    required String state,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(state, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetPowerstatConstMeta,
        argValues: [that, state],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetPowerstatConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_powerstat",
        argNames: ["that", "state"],
      );

  @override
  Future<void> crateApiRigHandleSetPtt({
    required RigHandle that,
    required bool tx,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_bool(tx, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetPttConstMeta,
        argValues: [that, tx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetPttConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_ptt",
    argNames: ["that", "tx"],
  );

  @override
  Future<void> crateApiRigHandleSetRit({
    required RigHandle that,
    required String vfo,
    required PlatformInt64 hz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_i_64(hz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetRitConstMeta,
        argValues: [that, vfo, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetRitConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_rit",
    argNames: ["that", "vfo", "hz"],
  );

  @override
  Future<void> crateApiRigHandleSetRptrOffs({
    required RigHandle that,
    required String vfo,
    required PlatformInt64 hz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_i_64(hz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetRptrOffsConstMeta,
        argValues: [that, vfo, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetRptrOffsConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_rptr_offs",
        argNames: ["that", "vfo", "hz"],
      );

  @override
  Future<void> crateApiRigHandleSetRptrShift({
    required RigHandle that,
    required String vfo,
    required String shift,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(shift, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetRptrShiftConstMeta,
        argValues: [that, vfo, shift],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetRptrShiftConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_rptr_shift",
        argNames: ["that", "vfo", "shift"],
      );

  @override
  Future<void> crateApiRigHandleSetSplitFreq({
    required RigHandle that,
    required String txVfo,
    required BigInt hz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(txVfo, serializer);
          sse_encode_u_64(hz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetSplitFreqConstMeta,
        argValues: [that, txVfo, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetSplitFreqConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_split_freq",
        argNames: ["that", "txVfo", "hz"],
      );

  @override
  Future<void> crateApiRigHandleSetSplitVfo({
    required RigHandle that,
    required String rxVfo,
    required bool split,
    required String txVfo,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(rxVfo, serializer);
          sse_encode_bool(split, serializer);
          sse_encode_String(txVfo, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 35,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetSplitVfoConstMeta,
        argValues: [that, rxVfo, split, txVfo],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetSplitVfoConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_set_split_vfo",
        argNames: ["that", "rxVfo", "split", "txVfo"],
      );

  @override
  Future<void> crateApiRigHandleSetTs({
    required RigHandle that,
    required String vfo,
    required BigInt hz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_u_64(hz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 36,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetTsConstMeta,
        argValues: [that, vfo, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetTsConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_ts",
    argNames: ["that", "vfo", "hz"],
  );

  @override
  Future<void> crateApiRigHandleSetXit({
    required RigHandle that,
    required String vfo,
    required PlatformInt64 hz,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_i_64(hz, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 37,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSetXitConstMeta,
        argValues: [that, vfo, hz],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSetXitConstMeta => const TaskConstMeta(
    debugName: "RigHandle_set_xit",
    argNames: ["that", "vfo", "hz"],
  );

  @override
  Future<List<String>> crateApiRigHandleSupportedFuncs({
    required RigHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 38,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSupportedFuncsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSupportedFuncsConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_supported_funcs",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiRigHandleSupportedLevels({
    required RigHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 39,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSupportedLevelsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSupportedLevelsConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_supported_levels",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiRigHandleSupportedModes({
    required RigHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 40,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSupportedModesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSupportedModesConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_supported_modes",
        argNames: ["that"],
      );

  @override
  Future<List<String>> crateApiRigHandleSupportedVfoOps({
    required RigHandle that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 41,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleSupportedVfoOpsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleSupportedVfoOpsConstMeta =>
      const TaskConstMeta(
        debugName: "RigHandle_supported_vfo_ops",
        argNames: ["that"],
      );

  @override
  Future<String?> crateApiRigHandleVfoByName({
    required RigHandle that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 42,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleVfoByNameConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleVfoByNameConstMeta => const TaskConstMeta(
    debugName: "RigHandle_vfo_by_name",
    argNames: ["that", "name"],
  );

  @override
  Future<List<String>> crateApiRigHandleVfoList({required RigHandle that}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 43,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleVfoListConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleVfoListConstMeta =>
      const TaskConstMeta(debugName: "RigHandle_vfo_list", argNames: ["that"]);

  @override
  Future<void> crateApiRigHandleVfoOp({
    required RigHandle that,
    required String vfo,
    required String op,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
            that,
            serializer,
          );
          sse_encode_String(vfo, serializer);
          sse_encode_String(op, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 44,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiRigHandleVfoOpConstMeta,
        argValues: [that, vfo, op],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRigHandleVfoOpConstMeta => const TaskConstMeta(
    debugName: "RigHandle_vfo_op",
    argNames: ["that", "vfo", "op"],
  );

  @override
  Future<void> crateApiFrbInit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 45,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFrbInitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFrbInitConstMeta =>
      const TaskConstMeta(debugName: "frb_init", argNames: []);

  @override
  Future<List<RadioModel>> crateApiListModels({required String driver}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(driver, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 46,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_radio_model,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiListModelsConstMeta,
        argValues: [driver],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListModelsConstMeta =>
      const TaskConstMeta(debugName: "list_models", argNames: ["driver"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RigHandle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RigHandle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RigHandle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RigHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RigHandle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RigHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RigHandle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RigHandleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  LevelValue dco_decode_box_autoadd_level_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_level_value(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  KeyValue dco_decode_key_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return KeyValue(
      key: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  LevelValue dco_decode_level_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return LevelValue_Float(dco_decode_f_32(raw[1]));
      case 1:
        return LevelValue_Int(dco_decode_i_32(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<KeyValue> dco_decode_list_key_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_key_value).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RadioModel> dco_decode_list_radio_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_radio_model).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  RadioModel dco_decode_radio_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RadioModel(
      driver: dco_decode_String(arr[0]),
      driverModelId: dco_decode_String(arr[1]),
      manufacturer: dco_decode_String(arr[2]),
      model: dco_decode_String(arr[3]),
      version: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
    );
  }

  @protected
  (bool, String) dco_decode_record_bool_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_bool(arr[0]), dco_decode_String(arr[1]));
  }

  @protected
  (String, int?) dco_decode_record_string_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_opt_box_autoadd_u_32(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RigHandle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RigHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RigHandle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RigHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RigHandle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RigHandleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  LevelValue sse_decode_box_autoadd_level_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_level_value(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  KeyValue sse_decode_key_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return KeyValue(key: var_key, value: var_value);
  }

  @protected
  LevelValue sse_decode_level_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_f_32(deserializer);
        return LevelValue_Float(var_field0);
      case 1:
        var var_field0 = sse_decode_i_32(deserializer);
        return LevelValue_Int(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<KeyValue> sse_decode_list_key_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <KeyValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_key_value(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RadioModel> sse_decode_list_radio_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RadioModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_radio_model(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RadioModel sse_decode_radio_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_driver = sse_decode_String(deserializer);
    var var_driverModelId = sse_decode_String(deserializer);
    var var_manufacturer = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return RadioModel(
      driver: var_driver,
      driverModelId: var_driverModelId,
      manufacturer: var_manufacturer,
      model: var_model,
      version: var_version,
      status: var_status,
    );
  }

  @protected
  (bool, String) sse_decode_record_bool_string(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_bool(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  (String, int?) sse_decode_record_string_opt_box_autoadd_u_32(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_opt_box_autoadd_u_32(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    RigHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RigHandleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    RigHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RigHandleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRigHandle(
    RigHandle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RigHandleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_level_value(
    LevelValue self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_level_value(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_key_value(KeyValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_level_value(LevelValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case LevelValue_Float(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_f_32(field0, serializer);
      case LevelValue_Int(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_i_32(field0, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_key_value(
    List<KeyValue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_key_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_radio_model(
    List<RadioModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_radio_model(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_radio_model(RadioModel self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.driver, serializer);
    sse_encode_String(self.driverModelId, serializer);
    sse_encode_String(self.manufacturer, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_record_bool_string(
    (bool, String) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_record_string_opt_box_autoadd_u_32(
    (String, int?) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_opt_box_autoadd_u_32(self.$2, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class RigHandleImpl extends RustOpaque implements RigHandle {
  // Not to be used by end users
  RigHandleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RigHandleImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RigHandle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RigHandle,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RigHandlePtr,
  );

  /// Returns the CTCSS squelch tone in units of 0.1 Hz.
  Future<int> getCtcssSql({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetCtcssSql(that: this, vfo: vfo);

  /// Returns the CTCSS TX tone in units of 0.1 Hz (e.g. 1318 = 131.8 Hz).
  Future<int> getCtcssTone({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetCtcssTone(that: this, vfo: vfo);

  /// Returns the DCS TX code.
  Future<int> getDcsCode({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetDcsCode(that: this, vfo: vfo);

  /// Returns the frequency of `vfo` in Hz.
  Future<BigInt> getFreq({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetFreq(that: this, vfo: vfo);

  /// Returns `true` if `func` is enabled on `vfo`.
  /// Use `supported_funcs()` to obtain valid function names.
  Future<bool> getFunc({required String vfo, required String func}) => RustLib
      .instance
      .api
      .crateApiRigHandleGetFunc(that: this, vfo: vfo, func: func);

  /// Returns the radio's identification string.
  Future<String> getInfo() =>
      RustLib.instance.api.crateApiRigHandleGetInfo(that: this);

  /// Returns the value of `level` on `vfo`.
  /// Use `supported_levels()` to obtain valid level names.
  Future<LevelValue> getLevel({required String vfo, required String level}) =>
      RustLib.instance.api.crateApiRigHandleGetLevel(
        that: this,
        vfo: vfo,
        level: level,
      );

  /// Returns `(mode_name, passband_hz)` for `vfo`.
  /// `passband_hz` is `None` when the radio reports its default bandwidth.
  Future<(String, int?)> getMode({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetMode(that: this, vfo: vfo);

  /// Returns the value of a radio-wide parameter.
  Future<LevelValue> getParm({required String parm}) =>
      RustLib.instance.api.crateApiRigHandleGetParm(that: this, parm: parm);

  /// Returns the radio power state: `"On"`, `"Off"`, `"Standby"`, or `"Operate"`.
  Future<String> getPowerstat() =>
      RustLib.instance.api.crateApiRigHandleGetPowerstat(that: this);

  /// Returns `true` if the radio is transmitting.
  Future<bool> getPtt() =>
      RustLib.instance.api.crateApiRigHandleGetPtt(that: this);

  /// Returns the RIT (Receive Incremental Tuning) offset in Hz.
  Future<PlatformInt64> getRit({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetRit(that: this, vfo: vfo);

  /// Returns the repeater offset in Hz.
  Future<PlatformInt64> getRptrOffs({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetRptrOffs(that: this, vfo: vfo);

  /// Returns the repeater shift direction: `"Simplex"`, `"Plus"`, or `"Minus"`.
  Future<String> getRptrShift({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetRptrShift(that: this, vfo: vfo);

  /// Returns the TX frequency in Hz when in split mode.
  Future<BigInt> getSplitFreq({required String txVfo}) => RustLib.instance.api
      .crateApiRigHandleGetSplitFreq(that: this, txVfo: txVfo);

  /// Returns `(split_enabled, tx_vfo_name)` for `rx_vfo`.
  Future<(bool, String)> getSplitVfo({required String rxVfo}) => RustLib
      .instance
      .api
      .crateApiRigHandleGetSplitVfo(that: this, rxVfo: rxVfo);

  /// Returns the VFO tuning step in Hz.
  Future<BigInt> getTs({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetTs(that: this, vfo: vfo);

  /// Returns the XIT (Transmit Incremental Tuning) offset in Hz.
  Future<PlatformInt64> getXit({required String vfo}) =>
      RustLib.instance.api.crateApiRigHandleGetXit(that: this, vfo: vfo);

  /// Sets the CTCSS squelch tone in units of 0.1 Hz.
  Future<void> setCtcssSql({required String vfo, required int tone}) => RustLib
      .instance
      .api
      .crateApiRigHandleSetCtcssSql(that: this, vfo: vfo, tone: tone);

  /// Sets the CTCSS TX tone in units of 0.1 Hz.
  Future<void> setCtcssTone({required String vfo, required int tone}) => RustLib
      .instance
      .api
      .crateApiRigHandleSetCtcssTone(that: this, vfo: vfo, tone: tone);

  /// Sets the DCS TX code.
  Future<void> setDcsCode({required String vfo, required int code}) => RustLib
      .instance
      .api
      .crateApiRigHandleSetDcsCode(that: this, vfo: vfo, code: code);

  /// Sets the frequency of `vfo` to `hz` Hz.
  Future<void> setFreq({required String vfo, required BigInt hz}) => RustLib
      .instance
      .api
      .crateApiRigHandleSetFreq(that: this, vfo: vfo, hz: hz);

  /// Enables or disables `func` on `vfo`.
  Future<void> setFunc({
    required String vfo,
    required String func,
    required bool enabled,
  }) => RustLib.instance.api.crateApiRigHandleSetFunc(
    that: this,
    vfo: vfo,
    func: func,
    enabled: enabled,
  );

  /// Sets `level` on `vfo` to `value`.
  Future<void> setLevel({
    required String vfo,
    required String level,
    required LevelValue value,
  }) => RustLib.instance.api.crateApiRigHandleSetLevel(
    that: this,
    vfo: vfo,
    level: level,
    value: value,
  );

  /// Sets the mode and optional passband width (Hz) on `vfo`.
  /// Pass `None` for `passband_hz` to use the radio's default width for the mode.
  Future<void> setMode({
    required String vfo,
    required String mode,
    int? passbandHz,
  }) => RustLib.instance.api.crateApiRigHandleSetMode(
    that: this,
    vfo: vfo,
    mode: mode,
    passbandHz: passbandHz,
  );

  /// Sets a radio-wide parameter.
  Future<void> setParm({required String parm, required LevelValue value}) =>
      RustLib.instance.api.crateApiRigHandleSetParm(
        that: this,
        parm: parm,
        value: value,
      );

  /// Sets the radio power state. Accepts `"On"`, `"Off"`, `"Standby"`, or `"Operate"`.
  Future<void> setPowerstat({required String state}) => RustLib.instance.api
      .crateApiRigHandleSetPowerstat(that: this, state: state);

  /// Keys the transmitter if `tx` is `true`, releases it if `false`.
  Future<void> setPtt({required bool tx}) =>
      RustLib.instance.api.crateApiRigHandleSetPtt(that: this, tx: tx);

  /// Sets the RIT offset in Hz (negative to tune down).
  Future<void> setRit({required String vfo, required PlatformInt64 hz}) =>
      RustLib.instance.api.crateApiRigHandleSetRit(
        that: this,
        vfo: vfo,
        hz: hz,
      );

  /// Sets the repeater offset in Hz.
  Future<void> setRptrOffs({required String vfo, required PlatformInt64 hz}) =>
      RustLib.instance.api.crateApiRigHandleSetRptrOffs(
        that: this,
        vfo: vfo,
        hz: hz,
      );

  /// Sets the repeater shift direction. Accepts `"Simplex"`, `"Plus"`, `"Minus"`,
  /// `"None"`, `"+"`, or `"-"` (case-insensitive).
  Future<void> setRptrShift({required String vfo, required String shift}) =>
      RustLib.instance.api.crateApiRigHandleSetRptrShift(
        that: this,
        vfo: vfo,
        shift: shift,
      );

  /// Sets the TX frequency in Hz when in split mode.
  Future<void> setSplitFreq({required String txVfo, required BigInt hz}) =>
      RustLib.instance.api.crateApiRigHandleSetSplitFreq(
        that: this,
        txVfo: txVfo,
        hz: hz,
      );

  /// Enables or disables split, assigning `tx_vfo` as the transmit VFO.
  Future<void> setSplitVfo({
    required String rxVfo,
    required bool split,
    required String txVfo,
  }) => RustLib.instance.api.crateApiRigHandleSetSplitVfo(
    that: this,
    rxVfo: rxVfo,
    split: split,
    txVfo: txVfo,
  );

  /// Sets the VFO tuning step in Hz.
  Future<void> setTs({required String vfo, required BigInt hz}) =>
      RustLib.instance.api.crateApiRigHandleSetTs(that: this, vfo: vfo, hz: hz);

  /// Sets the XIT offset in Hz.
  Future<void> setXit({required String vfo, required PlatformInt64 hz}) =>
      RustLib.instance.api.crateApiRigHandleSetXit(
        that: this,
        vfo: vfo,
        hz: hz,
      );

  /// Returns the function names this radio supports (e.g. `["Noise Blanker", "VOX"]`).
  Future<List<String>> supportedFuncs() =>
      RustLib.instance.api.crateApiRigHandleSupportedFuncs(that: this);

  /// Returns the level names this radio supports (e.g. `["AF Gain", "RF Power"]`).
  Future<List<String>> supportedLevels() =>
      RustLib.instance.api.crateApiRigHandleSupportedLevels(that: this);

  /// Returns the mode names this radio supports (e.g. `["USB", "LSB", "CW"]`).
  Future<List<String>> supportedModes() =>
      RustLib.instance.api.crateApiRigHandleSupportedModes(that: this);

  /// Returns the VFO operation names this radio supports.
  Future<List<String>> supportedVfoOps() =>
      RustLib.instance.api.crateApiRigHandleSupportedVfoOps(that: this);

  /// Returns the canonical name for `name` if this radio has such a VFO,
  /// or `None` if it does not. Accepts driver aliases (e.g. `"VFOA"` for `"A"`).
  Future<String?> vfoByName({required String name}) =>
      RustLib.instance.api.crateApiRigHandleVfoByName(that: this, name: name);

  /// Returns the VFO names supported by this radio (e.g. `["A", "B", "Current"]`).
  Future<List<String>> vfoList() =>
      RustLib.instance.api.crateApiRigHandleVfoList(that: this);

  /// Executes a discrete VFO operation (e.g. `"Toggle A/B"`, `"Copy A→B"`).
  /// Use `supported_vfo_ops()` to obtain the list of valid operation names.
  Future<void> vfoOp({required String vfo, required String op}) =>
      RustLib.instance.api.crateApiRigHandleVfoOp(that: this, vfo: vfo, op: op);
}
